In [1]:
import numpy as np
import pandas as pd

### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
(1/6) * (1/6)

0.027777777777777776

In [3]:
snake_eyes = 0.03
double = np.random.random((100000,2))
double


array([[0.92831554, 0.86968588],
       [0.46813415, 0.65346783],
       [0.45761913, 0.37654263],
       ...,
       [0.85337479, 0.66526233],
       [0.38222348, 0.79138079],
       [0.14183519, 0.7010062 ]])

In [4]:
double_eyes = double < snake_eyes
double_eyes

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
# amount of heads looking for divided by total trials
1.5 / 8
# .19 or 19% is the probability of getting exactly 3 heads

0.1875

In [33]:
flips = 8 
coin = ['H', 'T']
head_count = np.random.choice(coin, (100000, flips))
head_count

array([['T', 'T', 'H', ..., 'H', 'T', 'T'],
       ['H', 'T', 'H', ..., 'H', 'H', 'H'],
       ['H', 'T', 'T', ..., 'H', 'T', 'H'],
       ...,
       ['H', 'H', 'T', ..., 'T', 'T', 'H'],
       ['T', 'T', 'T', ..., 'H', 'H', 'H'],
       ['H', 'H', 'H', ..., 'T', 'T', 'T']], dtype='<U1')

In [34]:
((head_count == 'H').sum(axis=1) == 3)

array([ True, False, False, ..., False,  True, False])

In [38]:
((head_count == 'H').sum(axis=1) == 3).sum() / 100000

0.22208

In [39]:
((head_count == 'H').sum(axis=1) > 3).sum() / 100000

0.63557

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [8]:
webdev = .75
ds = .25

billboard = np.random.random((1000, 2))
billboard

array([[0.24606703, 0.25647147],
       [0.28028412, 0.71092986],
       [0.69009581, 0.01507407],
       ...,
       [0.83459819, 0.57516006],
       [0.07633783, 0.50942477],
       [0.76309694, 0.78092573]])

In [9]:
databoard = billboard < ds

In [10]:
(databoard.sum(axis=1) == 2).mean()

0.073

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [11]:
avgpop = 3
stdpop = 1.5
weekpop = 17
pop = np.random.normal(avgpop,stdpop, (10000,5))
pop


(pop.sum(axis=1) <= 16).mean() * 100

61.3

In [12]:
# creating a for loop that would append popleft - i to a new array/list

def popcount(pop):
    for i in pop:
        popleft = 17
        popleft -= i
        z = i.sum()
    return(z)

popcount(pop)

11.969223989487427

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, standard deviation of 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [13]:
men_mean = 178
men_std = 8
women_mean = 170
women_std = 6

men = np.random.normal(men_mean,men_std,100000)
men
women = np.random.normal(women_mean,women_std,100000)
women

array([174.76721313, 170.19880646, 174.96000221, ..., 175.60964483,
       164.05618397, 156.20135522])

In [14]:
comparison = (men < women)
comparison

array([ True, False,  True, ...,  True, False, False])

In [15]:
compare_sum = (comparison == True).sum()
compare_sum / len(men) * 100

21.387

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

 - What is the probability that we observe an installation issue within the first 150 students that download anaconda?

 - How likely is it that 450 students all download anaconda without an issue?

In [16]:
fail_chance = .004
download = np.random.random((100000,150))

fail = (download < fail_chance)
(fail.sum(axis=1) > 1).mean()

0.12117

In [17]:
fail_chance = .004
download = np.random.random((100000,450))

fail = (download < fail_chance)
(fail.sum(axis=1) > 1).mean()

0.53844

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
- How likely is it that a food truck will show up sometime this week?

In [18]:
truck_chance = .7

day_chance = np.random.random((10000,3))

truck = (day_chance < truck_chance)
truck
(truck.sum(axis=1) < True).mean() * 100

2.67

In [19]:
week_chance = np.random.random((10000,5))
truck = (week_chance < truck_chance)
(truck.sum(axis=1) > True).mean() * 100

96.81

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [20]:

n_trials = ncols = 23
n_simulations = nrows = 100_000

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday

array([[341, 282, 346, ..., 104, 178, 225],
       [142,  89, 268, ..., 144,  56, 117],
       [ 23, 189, 134, ..., 272,  98,  25],
       ...,
       [ 62,  88, 270, ...,  21, 163, 242],
       [308,  55, 143, ..., 280, 332,  46],
       [322, 312, 225, ..., 185, 278, 303]])

In [21]:
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.50943

In [22]:
# For 20 people:
n_trials = ncols = 20

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.41327

In [23]:
# For 40 people:
n_trials = ncols = 40

# Create matrix
birthday = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.89097